//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace T12地铁系统
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int AutoId { get; set; }
        public string UserName { get; set; }
        public string Begin { get; set; }
        public string End { get; set; }
        public Nullable<int> Count { get; set; }
        public System.DateTime BuyDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
